/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dc7u4OUMGH8
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export default function Home() {
  return (
    <>
      <div className="grid items-center min-h-[600px] gap-6 px-4 md:px-6 lg:gap-12 lg:min-h-[700px] xl:gap-16">
        <div className="flex items-center justify-center mt-20">
        <img
          alt="Image"
          className="aspect-video rounded-xl overflow-hidden object-cover object-center border"
          height="225"
          src="/placeholder.svg"
          width="400"
        />
                <img
          alt="Image"
          className="aspect-video rounded-xl overflow-hidden object-cover object-center border ml-20"
          height="225"
          src="/placeholder.svg"
          width="400"
        />
        </div>
            <div className="flex gap-1.5">
              <Input placeholder="Enter your bet" readOnly/>
              <Button>Place Bet</Button>
          </div>
          <div className="grid gap-6">
        <div className="bg-white dark:bg-gray-950 rounded-lg p-4">
          <h2 className="text-xl font-semibold mb-4">User Bids</h2>
          <ul className="divide-y divide-gray-200 dark:divide-gray-800">
            <li className="py-2">
              <div className="flex justify-between items-center">
                <span className="font-semibold">John Doe</span>
                <span className="text-green-500">Completed</span>
              </div>
            </li>
            <li className="py-2">
              <div className="flex justify-between items-center">
                <span className="font-semibold">Jane Smith</span>
                <span className="text-red-500">Incomplete</span>
              </div>
            </li>
            <li className="py-2">
              <div className="flex justify-between items-center">
                <span className="font-semibold">Alice Johnson</span>
                <span className="text-green-500">Completed</span>
              </div>
            </li>
            <li className="py-2">
              <div className="flex justify-between items-center">
                <span className="font-semibold">Bob Brown</span>
                <span className="text-green-500">Completed</span>
              </div>
            </li>
          </ul>
        </div>
      </div>

      </div>

    </>
  )
}
